name: Build SmartDNS Conf

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * 1"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "TAG_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "RELEASE_NAME=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
        shell: bash

      - name: Clone dnsmasq-china-list repo
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          depth: 1
          branch: 'master'
          owner: 'felixonmars'
          repository: 'dnsmasq-china-list'

      - name: Build SmartDNS Conf
        run: |
          cd dnsmasq-china-list
          make SERVER=domestic SMARTDNS_SPEEDTEST_MODE=tcp:80 smartdns-domain-rules
          cp *.domain.smartdns.conf /tmp

      - name: Checkout
        uses: actions/checkout@master
        with:
          token: ${{ secrets.GITHUB_TOKEN  }}

      - name: Commit files
        run: |
          cp /tmp/*.domain.smartdns.conf .
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -A
          git commit -m "${{ env.RELEASE_NAME }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
